// Generated by CoffeeScript 1.4.0
var app, c, fs, game, handler, io;

app = require('http').createServer(handler);

io = require('socket.io').listen(app);

fs = require('fs');

game = require('./game');

app.listen(9999);

handler = function(req, res) {
  return fs.readFile(__dirname + '/index.html', function(err, data) {
    if (err) {
      res.writeHead(500);
      return res.end('Error loading index.html');
    }
    res.writeHead(200);
    return res.end(data);
  });
};

c = new game.ServerController;

io.sockets.on('connection', function(socket) {
  return c.onconnect(socket);
});
